using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Localization;

namespace MatMail.Pages.Mail;

/// <summary>The shell of the web mail client. Everything else is done by the scripts through <c>/api/mail</c>.</summary>
public class IndexModel(IStringLocalizer<SharedResource> l) : PageModel
{
    /// <summary>The texts the scripts show (handed over as JSON, so the scripts need no translation files of their own).</summary>
    public IReadOnlyDictionary<string, string> Texts { get; private set; } = new Dictionary<string, string>();

    public void OnGet()
    {
        Texts = new Dictionary<string, string>
        {
            ["mail"] = l["Mail"],
            ["inbox"] = l["Inbox"],
            ["drafts"] = l["Drafts"],
            ["sent"] = l["Sent"],
            ["archive"] = l["Archive"],
            ["spam"] = l["Spam"],
            ["trash"] = l["Trash"],
            ["myMailbox"] = l["My mailbox"],
            ["newFolder"] = l["New folder"],
            ["folderName"] = l["Folder name"],
            ["renameFolder"] = l["Rename folder"],
            ["deleteFolder"] = l["Delete folder"],
            ["confirmDeleteFolder"] = l["Delete this folder with all its messages?"],
            ["markAllRead"] = l["Mark all as read"],
            ["emptyTrash"] = l["Empty trash now"],
            ["emptySpam"] = l["Delete all spam now"],
            ["confirmEmpty"] = l["Delete all messages in this folder for good?"],
            ["loadFailed"] = l["The mail could not be loaded."],
            ["noMailbox"] = l["You have no mailbox yet. Ask an administrator to create one for you."],
            ["noResults"] = l["No messages match your search."],
            ["nothingHere"] = l["Nothing here."],
            ["emptyInbox"] = l["Your inbox is empty."],
            ["emptySent"] = l["No sent messages."],
            ["emptyDrafts"] = l["You have no drafts."],
            ["emptyTrashText"] = l["The trash is empty."],
            ["emptySpamText"] = l["No spam."],
            ["emptyArchive"] = l["The archive is empty."],
            ["noSubject"] = l["(no subject)"],
            ["noRecipient"] = l["(no recipient)"],
            ["toPrefix"] = l["To:"],
            ["me"] = l["me"],
            ["select"] = l["Select"],
            ["selectAll"] = l["Select all"],
            ["all"] = l["All"],
            ["none"] = l["None"],
            ["read"] = l["Read"],
            ["unread"] = l["Unread"],
            ["starred"] = l["Starred"],
            ["notStarred"] = l["Not starred"],
            ["star"] = l["Star"],
            ["addStar"] = l["Add star"],
            ["removeStar"] = l["Remove star"],
            ["refresh"] = l["Refresh"],
            ["more"] = l["More"],
            ["archiveAction"] = l["Archive"],
            ["delete"] = l["Delete"],
            ["deleteForever"] = l["Delete forever"],
            ["reportSpam"] = l["Report spam"],
            ["notSpam"] = l["Not spam"],
            ["markRead"] = l["Mark as read"],
            ["markUnread"] = l["Mark as unread"],
            ["moveTo"] = l["Move to"],
            ["selectedCount"] = l["{0} selected"],
            ["pagerText"] = l["{0}–{1} of {2}"],
            ["newer"] = l["Newer"],
            ["older"] = l["Older"],
            ["movedToArchive"] = l["Moved to the archive."],
            ["moved"] = l["Moved."],
            ["movedToTrash"] = l["Moved to the trash."],
            ["movedToSpam"] = l["Reported as spam."],
            ["movedToInbox"] = l["Moved to the inbox."],
            ["deletedForever"] = l["Deleted for good."],
            ["confirmDeleteForever"] = l["Delete these messages for good? This cannot be undone."],
            ["undo"] = l["Undo"],
            ["back"] = l["Back"],
            ["messageGone"] = l["This message no longer exists."],
            ["messageBody"] = l["Message text"],
            ["from"] = l["From"],
            ["replyTo"] = l["Reply-To"],
            ["to"] = l["To"],
            ["cc"] = l["Cc"],
            ["bcc"] = l["Bcc"],
            ["date"] = l["Date"],
            ["deliveredFor"] = l["Delivered for"],
            ["print"] = l["Print"],
            ["downloadEml"] = l["Download message (.eml)"],
            ["showOriginal"] = l["Show original"],
            ["imagesBlocked"] = l["Pictures from the internet are blocked to protect your privacy."],
            ["showImages"] = l["Show pictures"],
            ["attachmentsCount"] = l["{0} attachment(s)"],
            ["reply"] = l["Reply"],
            ["replyAll"] = l["Reply all"],
            ["forward"] = l["Forward"],
            ["compose"] = l["Compose"],
            ["newMessage"] = l["New message"],
            ["minimize"] = l["Minimise"],
            ["fullScreen"] = l["Full screen"],
            ["saveAndClose"] = l["Save and close"],
            ["subject"] = l["Subject"],
            ["send"] = l["Send"],
            ["sending"] = l["Sending…"],
            ["saving"] = l["Saving…"],
            ["draftSaved"] = l["Draft saved."],
            ["messageSent"] = l["Message sent."],
            ["discardDraft"] = l["Discard draft"],
            ["confirmDiscard"] = l["Discard this message?"],
            ["sendWithoutSubject"] = l["Send this message without a subject?"],
            ["addRecipient"] = l["Add at least one recipient."],
            ["invalidRecipient"] = l["“{0}” is not a valid e-mail address."],
            ["tooManyWindows"] = l["Close a message window first."],
            ["noIdentity"] = l["You are not allowed to send mail: no sender address is assigned to you."],
            ["signature"] = l["Signature"],
            ["noSignature"] = l["No signature"],
            ["attachFiles"] = l["Attach files"],
            ["fileTooLarge"] = l["“{0}” is larger than {1} MB."],
            ["uploadFailed"] = l["The upload failed."],
            ["remove"] = l["Remove"],
            ["bold"] = l["Bold"],
            ["italic"] = l["Italic"],
            ["underline"] = l["Underline"],
            ["bulletList"] = l["Bulleted list"],
            ["numberedList"] = l["Numbered list"],
            ["link"] = l["Link"],
            ["clearFormatting"] = l["Clear formatting"],
            ["cancel"] = l["Cancel"],
            ["ok"] = l["OK"],
            ["close"] = l["Close"],
        };
    }
}
